"""Phase 1 结果汇总：从 dualpath_results.csv 读出结果并生成对比表"""
from __future__ import annotations

from pathlib import Path
import csv

PROJECT_ROOT = Path(__file__).resolve().parents[1]
CSV_PATH = PROJECT_ROOT / "runs" / "direction_c" / "dualpath_results.csv"

# 关注的核心 tag 前缀
TAG_ORDER = ["A1_", "A2_", "A0_", "A3_"]
FUSION_LABELS = {
    "none": "none",
    "multiplicative": "mult(γ=0.5,T=5)",
}

def main():
    if not CSV_PATH.exists():
        print(f"CSV not found: {CSV_PATH}")
        print("Make sure experiments are done and results are synced from server.")
        return

    rows = []
    with CSV_PATH.open("r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append(row)

    # Filter Phase 1 tags
    phase1 = [r for r in rows if any(r["run_tag"].startswith(p) for p in TAG_ORDER)]
    if not phase1:
        print("No Phase 1 results found in CSV.")
        print("Existing tags:", [r["run_tag"] for r in rows])
        return

    # Parse dataset and shot from run_tag
    # Format: A1_clipart1k_10shot_visualonly
    parsed = []
    for r in phase1:
        tag = r["run_tag"]
        parts = tag.split("_", 2)  # ["A1", "clipart1k", "10shot_visualonly"]
        prefix = parts[0]
        ds = parts[1]
        rest = parts[2]  # e.g. "10shot_visualonly" or "10shot_visualonly_dualpath"

        shot = None
        model = None
        for p in rest.split("_"):
            if p.endswith("shot"):
                shot = p.replace("shot", "")
            elif p == "visualonly":
                model = "Visual-Only"
            elif p == "daf":
                model = "DAF"
            elif p == "dualpath":
                pass  # indicates dual-path mode

        # Determine fusion mode from tag
        if prefix == "A1_" or prefix == "A0_":
            fusion = "none"
        elif prefix == "A2_" or prefix == "A3_":
            fusion = "mult(γ=0.5,T=5)"

        map50 = float(r["mAP50"])
        map50_95 = float(r["mAP50_95"])
        map75 = float(r["mAP75"])
        p = float(r["P"])
        r_rec = float(r["R"])

        parsed.append({
            "tag": tag,
            "dataset": ds,
            "shot": shot,
            "model": model,
            "fusion": fusion,
            "mAP50": map50,
            "mAP50_95": map50_95,
            "mAP75": map75,
            "P": p,
            "R": r_rec,
        })

    # Print comparison table
    datasets = sorted(set(p["dataset"] for p in parsed))
    shots = sorted(set(p["shot"] for p in parsed), key=int)

    print("# Phase 1: Cross-Dataset Validation Results\n")
    print(f"Generated from: {CSV_PATH}\n")

    for ds in datasets:
        print(f"## {ds.upper()}\n")
        print("| Shot | Model | Fusion | mAP50 | mAP50-95 | mAP75 | P | R |")
        print("|------|-------|--------|-------|----------|-------|------|------|")

        ds_rows = [p for p in parsed if p["dataset"] == ds]
        # Sort: shot asc, model: Visual-Only before DAF, fusion: none before mult
        model_order = {"Visual-Only": 0, "DAF": 1}
        fusion_order = {"none": 0, "mult(γ=0.5,T=5)": 1}
        ds_rows.sort(key=lambda x: (int(x["shot"]), model_order.get(x["model"], 99), fusion_order.get(x["fusion"], 99)))

        for p in ds_rows:
            print(f"| {p['shot']} | {p['model']} | {p['fusion']} | {p['mAP50']:.4f} | {p['mAP50_95']:.4f} | {p['mAP75']:.4f} | {p['P']:.3f} | {p['R']:.3f} |")

        # ΔmAP50 table
        print("\n**Dual-Path Gain over Baseline (Δ mAP50)**\n")
        print("| Shot | Visual-Only Δ | DAF Δ |")
        print("|------|--------------|-------|")

        for shot in shots:
            s_rows = [p for p in ds_rows if p["shot"] == shot]
            vo_none = next((p for p in s_rows if p["model"] == "Visual-Only" and p["fusion"] == "none"), None)
            vo_mult = next((p for p in s_rows if p["model"] == "Visual-Only" and p["fusion"] != "none"), None)
            daf_none = next((p for p in s_rows if p["model"] == "DAF" and p["fusion"] == "none"), None)
            daf_mult = next((p for p in s_rows if p["model"] == "DAF" and p["fusion"] != "none"), None)

            vo_delta = f"+{(vo_mult['mAP50']/vo_none['mAP50'] - 1)*100:.1f}%" if vo_none and vo_mult and vo_none['mAP50'] > 0 else "N/A"
            daf_delta = f"+{(daf_mult['mAP50']/daf_none['mAP50'] - 1)*100:.1f}%" if daf_none and daf_mult and daf_none['mAP50'] > 0 else "N/A"

            print(f"| {shot} | {vo_delta} | {daf_delta} |")

        print()

    # Summary findings
    print("## Key Findings\n")
    print("- **1-shot**: CLIP dual-path helps dramatically on both Visual-Only and DAF")
    print("- **10-shot**: ...(fill in after results)")

    print("\n---\n*Auto-generated by summarize_phase1.py*")


if __name__ == "__main__":
    main()
